### ISSUE TITLE
Build frontend for assigning a task

### ISSUE THREAD

**Issue by voxlol** [ktorng/ready-up#1]
https://github.com/ktorng/ready-up/blob/master/src/schema/crew/index.js

The Task, Mission, Card schemas aren't currently being used and may need updating. Game and player states are just stored in a JSON that is passed between client and server.

This mutation will probably take a gameId, a Task object, and a userId, and then update the corresponding gameState and playerState objects to assign that Task to the user.
 * A "player" is just a join record in the gameUsers table - I haven't been super consistent yet on when to use gameId+userId vs just playerId.
 

Local development is done by starting the graphql+subscription server in the root folder, and then starting up the react app separate in the /client folder. Uses sqlite in dev and postgres in prod.

**Comment by ktorng** [comment]
Repurposing this for frontend component work for assigning a task only and splitting out the graphql part (moved schema and resolver work to #4) 

Need to refactor some stuff, because game and player state and player objects are currently pretty badly organized
